/* eslint-disable prettier/prettier */
import { Injectable } from '@nestjs/common';
import { Role } from './roles/role.enum';
import { User } from './user';

@Injectable()
export class UserService {
   private users: User[] = [
        new User(1, "admin", "admin", [Role.ADMIN]),
        new User(2, "user", "user", [Role.USER]),
        new User(3, "carrito_admin", "carrito_admin", [Role.CARRITO_ADMIN]),
        new User(4, "categoria_admin", "categoria_admin", [Role.CATEGORIA_ADMIN]),
        new User(5, "carrito_regalo_admin", "carrito_regalo_admin", [Role.CARRITO_REGALO_ADMIN]),
        new User(6, "categoria_regalo_admin", "categoria_regalo_admin", [Role.CATEGORIA_REGALO_ADMIN]),
        new User(7, "carrito_lectura", "carrito_lectura", [Role.CARRITO_LECTURA]),
        new User(8, "categoria_lectura", "categoria_lectura", [Role.CATEGORIA_LECTURA]),
        new User(9, "carrito_regalo_lectura", "carrito_regalo_lectura", [Role.CARRITO_REGALO_LECTURA]),
        new User(10, "categoria_regalo_lectura", "categoria_regalo_lectura", [Role.CATEGORIA_REGALO_LECTURA]),
        new User(11, "carrito_escritura", "carrito_escritura", [Role.CARRITO_ESCRITURA]),
        new User(12, "categoria_escritura", "categoria_escritura", [Role.CATEGORIA_ESCRITURA]),
        new User(13, "carrito_regalo_escritura", "carrito_regalo_escritura", [Role.CARRITO_REGALO_ESCRITURA]),
        new User(14, "categoria_regalo_escritura", "categoria_regalo_escritura", [Role.CATEGORIA_REGALO_ESCRITURA]),
        new User(15, "carrito_eliminacion", "carrito_eliminacion", [Role.CARRITO_ELIMINACION]),
        new User(16, "categoria_eliminacion", "categoria_eliminacion", [Role.CATEGORIA_ELIMINACION]),
        new User(17, "carrito_regalo_eliminacion", "carrito_regalo_eliminacion", [Role.CARRITO_REGALO_ELIMINACION]),
        new User(18, "categoria_regalo_eliminacion", "categoria_regalo_eliminacion", [Role.CATEGORIA_REGALO_ELIMINACION]),
        new User(19, "usuario_admin", "usuario_admin", [Role.USUARIO_ADMIN]),
        new User(20, "usuario_lectura", "usuario_lectura", [Role.USUARIO_LECTURA]),
        new User(21, "usuario_escritura", "usuario_escritura", [Role.USUARIO_ESCRITURA]),
        new User(22, "usuario_eliminacion", "usuario_eliminacion", [Role.USUARIO_ELIMINACION]),
        new User(23, "usuario_usuario_admin", "usuario_usuario_admin", [Role.USUARIO_USUARIO_ADMIN]),
        new User(24, "usuario_usuario_lectura", "usuario_usuario_lectura", [Role.USUARIO_USUARIO_LECTURA]),
        new User(25, "usuario_usuario_escritura", "usuario_usuario_escritura", [Role.USUARIO_USUARIO_ESCRITURA]),
        new User(26, "usuario_usuario_eliminacion", "usuario_usuario_eliminacion", [Role.USUARIO_USUARIO_ELIMINACION]),
        new User(23, "usuario_categoria_admin", "usuario_categoria_admin", [Role.USUARIO_CATEGORIA_ADMIN]),
        new User(24, "usuario_categoria_lectura", "usuario_categoria_lectura", [Role.USUARIO_CATEGORIA_LECTURA]),
        new User(25, "usuario_categoria_escritura", "usuario_categoria_escritura", [Role.USUARIO_CATEGORIA_ESCRITURA]),
        new User(26, "usuario_categoria_eliminacion", "usuario_categoria_eliminacion", [Role.USUARIO_CATEGORIA_ELIMINACION]),
        new User(27, "resena_admin", "resena_admin", [Role.RESENA_ADMIN]),
        new User(28, "resena_lectura", "resena_lectura", [Role.RESENA_LECTURA]),
        new User(29, "resena_escritura", "resena_escritura", [Role.RESENA_ESCRITURA]),
        new User(30, "resena_eliminacion", "resena_eliminacion", [Role.RESENA_ELIMINACION]),
        new User(31, "regalo_resena_admin", "regalo_resena_admin", [Role.REGALO_RESENA_ADMIN]),
        new User(32, "regalo_resena_lectura", "regalo_resena_lectura", [Role.REGALO_RESENA_LECTURA]),
        new User(33, "regalo_resena_escritura", "regalo_resena_escritura", [Role.REGALO_RESENA_ESCRITURA]),
        new User(34, "regalo_resena_eliminacion", "regalo_resena_eliminacion", [Role.REGALO_RESENA_ELIMINACION]),
        new User(35, "usuario_resena_admin", "usuario_resena_admin", [Role.USUARIO_RESENA_ADMIN]),
        new User(36, "usuario_resena_lectura", "usuario_resena_lectura", [Role.USUARIO_RESENA_LECTURA]),
        new User(37, "usuario_resena_escritura", "usuario_resena_escritura", [Role.USUARIO_RESENA_ESCRITURA]),
        new User(38, "usuario_resena_eliminacion", "usuario_resena_eliminacion", [Role.USUARIO_RESENA_ELIMINACION]),
        new User(39, "usuario_wishlist_admin", "usuario_wishlist_admin", [Role.USUARIO_WISHLIST_ADMIN]),
        new User(40, "usuario_wishlist_lectura", "usuario_wishlist_lectura", [Role.USUARIO_WISHLIST_LECTURA]),
        new User(41, "usuario_wishlist_escritura", "usuario_wishlist_escritura", [Role.USUARIO_WISHLIST_ESCRITURA]),
        new User(42, "usuario_wishlist_eliminacion", "usuario_wishlist_eliminacion", [Role.USUARIO_WISHLIST_ELIMINACION]),
        new User(43, "wishlist_admin", "wishlist_admin", [Role.WISHLIST_ADMIN]),
        new User(44, "wishlist_escritura", "wishlist_escritura", [Role.WISHLIST_ESCRITURA]),
        new User(45, "wishlist_lectura", "wishlist_lectura", [Role.WISHLIST_LECTURA]),
        new User(46, "wishlist_eliminacion", "wishlist_eliminacion", [Role.WISHLIST_ELIMINACION]),
        new User(47, "regalo_admin", "regalo_admin", [Role.REGALO_ADMIN]),
        new User(48, "regalo_escritura", "regalo_escritura", [Role.REGALO_ESCRITURA]),
        new User(49, "regalo_lectura", "regalo_lectura", [Role.REGALO_LECTURA]),
        new User(50, "regalo_eliminacion", "regalo_eliminacion", [Role.REGALO_ELIMINACION]),
        new User(51, "wishlist_regalo_admin", "wishlist_regalo_admin", [Role.WISHLIST_REGALO_ADMIN]),
        new User(52, "wishlist_regalo_escritura", "wishlist_regalo_escritura", [Role.WISHLIST_REGALO_ESCRITURA]),
        new User(53, "wishlist_regalo_lectura", "wishlist_regalo_lectura", [Role.WISHLIST_REGALO_LECTURA]),
        new User(54, "wishlist_regalo_eliminacion", "wishlist_regalo_eliminacion", [Role.WISHLIST_REGALO_ELIMINACION]),
        new User(55, "regalo_categoria_admin", "regalo_categoria_admin", [Role.REGALO_CATEGORIA_ADMIN]),
        new User(56, "regalo_categoria_escritura", "regalo_categoria_escritura", [Role.REGALO_CATEGORIA_ESCRITURA]),
        new User(57, "regalo_categoria_lectura", "regalo_categoria_lectura", [Role.REGALO_CATEGORIA_LECTURA]),
        new User(58, "regalo_categoria_eliminacion", "regalo_categoria_eliminacion", [Role.REGALO_CATEGORIA_ELIMINACION]),
        new User(59, "regalo_tienda_admin", "regalo_tienda_admin", [Role.REGALO_TIENDA_ADMIN]),
        new User(60, "regalo_tienda_escritura", "regalo_tienda_escritura", [Role.REGALO_TIENDA_ESCRITURA]),
        new User(61, "regalo_tienda_lectura", "regalo_tienda_lectura", [Role.REGALO_TIENDA_LECTURA]),
        new User(62, "regalo_tienda_eliminacion", "regalo_tienda_eliminacion", [Role.REGALO_TIENDA_ELIMINACION]),
        new User(63, "tienda_admin", "tienda_admin", [Role.TIENDA_ADMIN]),
        new User(64, "tienda_escritura", "tienda_escritura", [Role.TIENDA_ESCRITURA]),
        new User(65, "tienda_lectura", "tienda_lectura", [Role.TIENDA_LECTURA]),
        new User(66, "tienda_eliminacion", "tienda_eliminacion", [Role.TIENDA_ELIMINACION]),
        new User(67, "localizacion_admin", "localizacion_admin", [Role.LOCALIZACION_ADMIN]),
        new User(68, "localizacion_escritura", "localizacion_escritura", [Role.LOCALIZACION_ESCRITURA]),
        new User(69, "localizacion_lectura", "localizacion_lectura", [Role.LOCALIZACION_LECTURA]),
        new User(70, "localizacion_eliminacion", "localizacion_eliminacion", [Role.LOCALIZACION_ELIMINACION]),
        new User(71, "tienda_localizacion_admin", "tienda_localizacion_admin", [Role.TIENDA_LOCALIZACION_ADMIN]),
        new User(72, "tienda_localizacion_escritura", "tienda_localizacion_escritura", [Role.TIENDA_LOCALIZACION_ESCRITURA]),
        new User(73, "tienda_localizacion_lectura", "tienda_localizacion_lectura", [Role.TIENDA_LOCALIZACION_LECTURA]),
        new User(74, "tienda_localizacion_eliminacion", "tienda_localizacion_eliminacion", [Role.TIENDA_LOCALIZACION_ELIMINACION]),
        new User(75, "usuario_direcciones_admin", "usuario_direcciones_admin", [Role.USUARIO_DIRECCIONES_ADMIN]),
        new User(76, "usuario_direcciones_escritura", "usuario_direcciones_escritura", [Role.USUARIO_DIRECCIONES_ESCRITURA]),
        new User(77, "usuario_direcciones_lectura", "usuario_direcciones_lectura", [Role.USUARIO_DIRECCIONES_LECTURA]),
        new User(78, "usuario_direcciones_eliminacion", "usuario_direcciones_eliminacion", [Role.USUARIO_DIRECCIONES_ELIMINACION]),
        new User(79, "tienda_regalo_admin", "tienda_regalo_admin", [Role.TIENDA_REGALO_ADMIN]),
        new User(80, "tienda_regalo_escritura", "tienda_regalo_escritura", [Role.TIENDA_REGALO_ESCRITURA]),
        new User(81, "tienda_regalo_lectura", "tienda_regalo_lectura", [Role.TIENDA_REGALO_LECTURA]),
        new User(82, "tienda_regalo_eliminacion", "tienda_regalo_eliminacion", [Role.TIENDA_REGALO_ELIMINACION]),
    ];

   async findOne(username: string): Promise<User | undefined> {
       return this.users.find(user => user.username === username);
   }

   async findOneById(id: number): Promise<User | undefined> {
    return this.users.find(user => user.id === id);
    }
}